# Generated by Django 5.2.10 on 2026-01-26 00:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("upstream", "0002_add_performance_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="claimrecord",
            name="cpt",
            field=models.CharField(
                db_index=True, help_text="CPT procedure code", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="claimrecord",
            name="cpt_group",
            field=models.CharField(
                db_index=True,
                default="OTHER",
                help_text="CPT code group for analytics",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="claimrecord",
            name="payer",
            field=models.CharField(
                db_index=True, help_text="Insurance payer name", max_length=255
            ),
        ),
        migrations.AddIndex(
            model_name="claimrecord",
            index=models.Index(
                fields=["customer", "payer", "outcome", "submitted_date"],
                name="claim_payer_outcome_idx",
            ),
        ),
    ]
