# Generated by Django 5.2.10 on 2026-01-26 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("upstream", "0003_optimize_claim_indexes_crit3"),
    ]

    operations = [
        migrations.AlterField(
            model_name="claimrecord",
            name="upload",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="claim_records",
                to="upstream.upload",
            ),
        ),
    ]
