# Generated by Django 5.2.10 on 2026-01-26 03:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("upstream", "0005_add_unique_constraints_hash_fields_high12"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="claimrecord",
            index=models.Index(
                fields=["customer", "upload", "source_data_hash"],
                name="claim_source_hash_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="upload",
            index=models.Index(
                fields=["customer", "uploaded_at"], name="upload_cust_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="upload",
            index=models.Index(
                fields=["customer", "status"], name="upload_cust_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="upload",
            index=models.Index(
                fields=["customer", "file_hash"], name="upload_file_hash_idx"
            ),
        ),
    ]
