# Generated by Django 5.2.10 on 2026-01-26 17:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upstream", "0012_add_check_constraints_phase3"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="claimvalidationhistory",
            constraint=models.CheckConstraint(
                condition=models.Q(("error_count__gte", 0)),
                name="cvh_error_count_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="claimvalidationhistory",
            constraint=models.CheckConstraint(
                condition=models.Q(("warning_count__gte", 0)),
                name="cvh_warning_count_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="claimvalidationhistory",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("quality_score__gte", 0.0), ("quality_score__lte", 1.0)),
                    ("quality_score__isnull", True),
                    _connector="OR",
                ),
                name="cvh_quality_score_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="dataanomalydetection",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("anomaly_score__gte", 0.0), ("anomaly_score__lte", 1.0)
                ),
                name="dad_anomaly_score_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="dataanomalydetection",
            constraint=models.CheckConstraint(
                condition=models.Q(("confidence__gte", 0.0), ("confidence__lte", 1.0)),
                name="dad_confidence_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="dataanomalydetection",
            constraint=models.CheckConstraint(
                condition=models.Q(("affected_row_count__gte", 0)),
                name="dad_affected_rows_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="dataqualitymetric",
            constraint=models.CheckConstraint(
                condition=models.Q(("score__gte", 0.0), ("score__lte", 1.0)),
                name="dqm_score_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="dataqualitymetric",
            constraint=models.CheckConstraint(
                condition=models.Q(("sample_size__gte", 0)),
                name="dqm_sample_size_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="dataqualitymetric",
            constraint=models.CheckConstraint(
                condition=models.Q(("passed_count__gte", 0)),
                name="dqm_passed_count_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="dataqualitymetric",
            constraint=models.CheckConstraint(
                condition=models.Q(("failed_count__gte", 0)),
                name="dqm_failed_count_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="dataqualitymetric",
            constraint=models.CheckConstraint(
                condition=models.Q(("passed_count__lte", models.F("sample_size"))),
                name="dqm_passed_lte_sample",
            ),
        ),
        migrations.AddConstraint(
            model_name="dataqualitymetric",
            constraint=models.CheckConstraint(
                condition=models.Q(("failed_count__lte", models.F("sample_size"))),
                name="dqm_failed_lte_sample",
            ),
        ),
    ]
