# Generated by Django 5.2.10 on 2026-01-26 22:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upstream", "0015_add_unique_constraint_driftevent_phase2"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="alertrule",
            index=models.Index(
                fields=["customer", "enabled"], name="idx_alertrule_customer_enabled"
            ),
        ),
    ]
