# Generated by Django 5.2.10 on 2026-01-27 16:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("upstream", "0022_add_automation_rule"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AutomationRule",
        ),
        migrations.DeleteModel(
            name="RiskBaseline",
        ),
    ]
