# Generated by Django 5.2.10 on 2026-01-27 16:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("upstream", "0023_add_execution_log"),
        ("upstream", "0023_claimrecord_submitted_via_authorization_executionlog"),
    ]

    operations = []
